using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CollectionViewMemoryLeak.Models
{
    public class CDE_ENT
    {
        public short zzmaj { get; set; }
        public string zzutil { get; set; }
        public string zzposte { get; set; }
        public string zzdate { get; set; }
        public string zzheure { get; set; }
        public int zzsynchro { get; set; }
        public string cde { get; set; }
        public string date_cde { get; set; }
        public string client { get; set; }
        public string date_creation { get; set; }
        public string heure_creation { get; set; }
        public string numero_caisse { get; set; }
        public string type_cli { get; set; }
        public string poste_bloque { get; set; }
        public string cde_type { get; set; }
        public string avoirfact { get; set; }
        public string type_avoir { get; set; }
        public string facture_origine { get; set; }
        public string date_facture_origine { get; set; }
        public string bl_origine { get; set; }
        public string date_origine { get; set; }
        public string regbl { get; set; }
        public string regroup { get; set; }
        public string regroup_facture { get; set; }
        public string gestion_alcool { get; set; }
        public string gestion_ordonnance { get; set; }
        public string refcli1 { get; set; }
        public string refcli2 { get; set; }
        public string status_cde { get; set; }
        public string intra_suivi { get; set; }
        public string intra_pays { get; set; }
        public string intra_region { get; set; }
        public string intra_cndlivr { get; set; }
        public string intra_cmpllivr { get; set; }
        public string intra_modetrsp { get; set; }
        public string flgdeb { get; set; }
        public string date_deb { get; set; }
        public string remise_taxe_ligne { get; set; }
        public string orgpay { get; set; }
        public string group1 { get; set; }
        public string group2 { get; set; }
        public string adherent1 { get; set; }
        public string adherent2 { get; set; }
        public string fam1 { get; set; }
        public string fam2 { get; set; }
        public string fam3 { get; set; }
        public string fam4 { get; set; }
        public string subvention { get; set; }
        public string article_trace { get; set; }
        public string opebon { get; set; }
        public string opcmde { get; set; }
        public string orig { get; set; }
        public string tarif { get; set; }
        public string lot_marche { get; set; }
        public string tarif2 { get; set; }
        public string cond_spec_gen { get; set; }
        public string promo_spec_gen { get; set; }
        public string cptventil { get; set; }
        public string facture { get; set; }
        public string datefact { get; set; }
        public string facture_date_edition { get; set; }
        public string facture_heure_edition { get; set; }
        public string empreinte { get; set; }
        public double ttc { get; set; }
        public double ttc_facture { get; set; }
        public string regl { get; set; }
        public string eche { get; set; }
        public string eche_calc { get; set; }
        public short rpeche { get; set; }
        public string eche_manuelle { get; set; }
        public string dateeche1 { get; set; }
        public short nbeche { get; set; }
        public string perfact { get; set; }
        public string flgfixfac { get; set; }
        public short fact_nbex { get; set; }
        public string perrel { get; set; }
        public string flgfixrel { get; set; }
        public string flgnetfac { get; set; }
        public string infofact { get; set; }
        public string textfact { get; set; }
        public string langue { get; set; }
        public string devise { get; set; }
        public double tauxdevise { get; set; }
        public string flgttc { get; set; }
        public string vendeur { get; set; }
        public string representant { get; set; }
        public double com_rep { get; set; }
        public double escompte { get; set; }
        public string typrem { get; set; }
        public double valrem { get; set; }
        public string remise1_calc { get; set; }
        public double remise1_taux { get; set; }
        public double remise1_val { get; set; }
        public string remise2_calc { get; set; }
        public double remise2_taux { get; set; }
        public double remise2_val { get; set; }
        public string remise3_calc { get; set; }
        public double remise3_taux { get; set; }
        public double remise3_val { get; set; }
        public string typrist { get; set; }
        public double valrist { get; set; }
        public string nu_loge { get; set; }
        public string depart_rendu { get; set; }
        public short controle_saisie { get; set; }
        public string flgbon { get; set; }
        public string flag_etat_beeper { get; set; }
        public string flgreliquat { get; set; }
        public string datebon { get; set; }
        public string flgedbon { get; set; }
        public string flgchbon { get; set; }
        public string flgvalbon { get; set; }
        public string flgalcool { get; set; }
        public string flgeddcsa { get; set; }
        public string flgconsigne_valorise { get; set; }
        public short nbex { get; set; }
        public string flgfranco { get; set; }
        public double port { get; set; }
        public string transporteur { get; set; }
        public string transitaire { get; set; }
        public string livreur { get; set; }
        public string camion { get; set; }
        public string secteur { get; set; }
        public string tournee { get; set; }
        public string tournee_etat { get; set; }
        public string tournee_origine { get; set; }
        public string ordrelivr { get; set; }
        public string ordrelivr_origine { get; set; }
        public string datelivr { get; set; }
        public string infolivr1 { get; set; }
        public string infolivr2 { get; set; }
        public string textlivr { get; set; }
        public string heureramasse { get; set; }
        public string recepisse { get; set; }
        public string heureminlivr { get; set; }
        public string heuremaxlivr { get; set; }
        public string heuresouhaitee { get; set; }
        public string titre { get; set; }
        public string raison { get; set; }
        public string raison2 { get; set; }
        public string adr1 { get; set; }
        public string adr2 { get; set; }
        public string adr3 { get; set; }
        public string ccp { get; set; }
        public string ville { get; set; }
        public string pays { get; set; }
        public string num_tel { get; set; }
        public string noadrlivr { get; set; }
        public string titrelivr { get; set; }
        public string raisonlivr { get; set; }
        public string adr1livr { get; set; }
        public string adr2livr { get; set; }
        public string adr3livr { get; set; }
        public string ccplivr { get; set; }
        public string villelivr { get; set; }
        public string payslivr { get; set; }
        public string noadrenlev { get; set; }
        public string titreenlev { get; set; }
        public string raisonenlev { get; set; }
        public string adr1enlev { get; set; }
        public string adr2enlev { get; set; }
        public string adr3enlev { get; set; }
        public string cpenlev { get; set; }
        public string villeenlev { get; set; }
        public string paysenlev { get; set; }
        public string flginter_site { get; set; }
        public string flgcompta { get; set; }
        public string flgedi { get; set; }
        public string impu_compta { get; set; }
        public string compta { get; set; }
        public string compta_consigne { get; set; }
        public string ctaxe1 { get; set; }
        public string ctaxe2 { get; set; }
        public string ctaxe3 { get; set; }
        public string ctaxe4 { get; set; }
        public string ctaxe5 { get; set; }
        public string ctaxe6 { get; set; }
        public string ctaxe7 { get; set; }
        public string ctaxe8 { get; set; }
        public string ctaxe9 { get; set; }
        public string ctaxe10 { get; set; }
        public double colis { get; set; }
        public double piece { get; set; }
        public double pbrut { get; set; }
        public double tare { get; set; }
        public double pnet { get; set; }
        public double pnet_piece { get; set; }
        public double pnet_colis { get; set; }
        public double nbpal { get; set; }
        public double mnthtbrut { get; set; }
        public double mntrem { get; set; }
        public double mntpromo { get; set; }
        public double mntesc { get; set; }
        public double mntrist { get; set; }
        public double htnet { get; set; }
        public double mntcons { get; set; }
        public double mntdecons { get; set; }
        public short nblig { get; set; }
        public short nbligart { get; set; }
        public double htbrutdev { get; set; }
        public double remdev { get; set; }
        public double promodev { get; set; }
        public double escptdev { get; set; }
        public double ristdev { get; set; }
        public double htnetdev { get; set; }
        public double consdev { get; set; }
        public double deconsdev { get; set; }
        public double totachat { get; set; }
        public double totrevient { get; set; }
        public double totrevient_tarif_reel { get; set; }
        public double totrevient_tarif_reel2 { get; set; }
        public double tot_subvention { get; set; }
        public double ht_valorise { get; set; }
        public double rem_diff_valorise { get; set; }
        public double netstatlig { get; set; }
        public double netstat { get; set; }
        public double margbrut { get; set; }
        public double margnet { get; set; }
        public string flgval { get; set; }
        public double htbrut_bl { get; set; }
        public double htnet_bl { get; set; }
        public string bord_charge_separe { get; set; }
        public double prep_colis { get; set; }
        public double prep_pendus { get; set; }
        public string prep_info1 { get; set; }
        public string prep_info2 { get; set; }
        public string prep_info3 { get; set; }
        public string prep_flgedit { get; set; }
        public string prep { get; set; }
        public string peseur { get; set; }
        public string prep_liste { get; set; }
        public double prep_pal { get; set; }
        public string fr1_calc { get; set; }
        public double fr1_val { get; set; }
        public string fr1_unit { get; set; }
        public string fr1_code { get; set; }
        public double fr1_valorise { get; set; }
        public string fr2_calc { get; set; }
        public double fr2_val { get; set; }
        public string fr2_unit { get; set; }
        public string fr2_code { get; set; }
        public double fr2_valorise { get; set; }
        public string fr3_calc { get; set; }
        public double fr3_val { get; set; }
        public string fr3_unit { get; set; }
        public string fr3_code { get; set; }
        public double fr3_valorise { get; set; }
        public string fr4_calc { get; set; }
        public double fr4_val { get; set; }
        public string fr4_unit { get; set; }
        public string fr4_code { get; set; }
        public double fr4_valorise { get; set; }
        public string fr5_calc { get; set; }
        public double fr5_val { get; set; }
        public string fr5_unit { get; set; }
        public string fr5_code { get; set; }
        public double fr5_valorise { get; set; }
        public string fr6_calc { get; set; }
        public double fr6_val { get; set; }
        public string fr6_unit { get; set; }
        public string fr6_code { get; set; }
        public double fr6_valorise { get; set; }
        public string cde_ref { get; set; }
        public string bl_ref { get; set; }
        public string cde_flg { get; set; }
        public string cde_emis { get; set; }
        public string cde_conf { get; set; }
        public string cde_info { get; set; }
        public string cde_texte { get; set; }
        public string cde_date { get; set; }
        public short cde_nbex { get; set; }
        public string cde_date_debut { get; set; }
        public string cde_heure_debut { get; set; }
        public string cde_date_fin { get; set; }
        public string cde_heure_fin { get; set; }
        public double cde_duree { get; set; }
        public string trsp_flg { get; set; }
        public string trsp_emis { get; set; }
        public string trsp_ref { get; set; }
        public string trsp_conf { get; set; }
        public string trsp_info { get; set; }
        public string trsp_texte { get; set; }
        public string trsp_date { get; set; }
        public short trsp_nbex { get; set; }
        public string trans_flg { get; set; }
        public string trans_emis { get; set; }
        public string trans_ref { get; set; }
        public string trans_conf { get; set; }
        public string trans_info { get; set; }
        public string trans_texte { get; set; }
        public string trans_date { get; set; }
        public short trans_nbex { get; set; }
        public string bl_flg { get; set; }
        public string bl_emis { get; set; }
        public string bl_conf { get; set; }
        public string bl_info { get; set; }
        public string bl_texte { get; set; }
        public string bl_date { get; set; }
        public short bl_nbex { get; set; }
        public string cde_ref_regroup { get; set; }
        public string orig_reliquat { get; set; }
        public string flag_controle_ok { get; set; }
        public string raison2livr { get; set; }
        public string flgexport { get; set; }
        public string frs_transporteur { get; set; }
        public string flgetat { get; set; }
        public string depot { get; set; }
        public string consigne_traitee { get; set; }
        public string telephone { get; set; }
    }
}
